repos:
  - repo: https://github.com/RichDom2185/nus-cs2103t-tp-git-hooks
    rev: v0.2.1
    hooks:
      - id: cpd
      - id: check-no-tabs
        exclude: ^Makefile$
      - id: check-eof-newline
      - id: check-trailing-whitespace
      - id: checkstyle
        args: ["-c", "config/checkstyle/checkstyle.xml"]
