title: "FoodRem"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

collections:
  - glossary

repository: "AY2223S1-CS2103T-W16-2/tp"
master_url: "https://github.com/AY2223S1-CS2103T-W16-2/tp/tree/master"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
