name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  jarfile:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          ref: master
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          java-package: jdk+fx
      - name: Create JAR file
        run: ./gradlew shadowJar
      - name: Generate tag name from time
        id: time
        run: echo ::set-output name=NOW::$(echo ${{ github.event.repository.updated_at}} | sed -e 's/-//g' -e 's/T/-/g' -e 's/.\{4\}$/Z/' -e 's/://g')
      - name: Create release on GitHub
        id: create_release # We need the id to refer to it in the next step
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.time.outputs.NOW }}
          release_name: Auto-release ${{ github.event.repository.updated_at}}
          body: 'Auto-created release from branch "${{ github.ref_name }}"'
      - name: Upload JAR file to GitHub releases
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/libs/foodrem.jar
          asset_name: foodrem.jar
          asset_content_type: application/java-archive
