name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  jarfile:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repositoru
        uses: actions/checkout@main
        with:
          ref: master
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          java-package: jdk+fx
      - name: Create JAR file
        run: ./gradlew shadowJar
      - name: Create release on GitHub
        id: create_release # We need the id to refer to it in the next step
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: Auto-created release from ${{ github.ref }}
      - name: Upload JAR file to GitHub releases
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/libs/foodrem.jar
          asset_name: foodrem.jar
          asset_content_type: application/java-archive
