name: Check all links on website are valid

on: [push, pull_request, workflow_dispatch]

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v5
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
      - name: Set up server dependencies
        working-directory: ${{ github.workspace }}/docs
        run: gem install --user-install bundler && bundle install
      - name: Set up checker dependencies
        working-directory: ${{ github.workspace }}/cli-test/linkchecker
        run: npm install
      - name: Set up server and check all links are valid
        working-directory: ${{ github.workspace }}/cli-test/linkchecker
        run: python serve-and-check.py
